/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as NormativasRouteImport } from './routes/normativas'
import { Route as LinksDeInteresRouteImport } from './routes/links-de-interes'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CalidadRouteImport } from './routes/calidad'
import { Route as AcercaDeNosotrosRouteImport } from './routes/acerca-de-nosotros'
import { Route as IndexRouteImport } from './routes/index'

const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const NormativasRoute = NormativasRouteImport.update({
  id: '/normativas',
  path: '/normativas',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksDeInteresRoute = LinksDeInteresRouteImport.update({
  id: '/links-de-interes',
  path: '/links-de-interes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CalidadRoute = CalidadRouteImport.update({
  id: '/calidad',
  path: '/calidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AcercaDeNosotrosRoute = AcercaDeNosotrosRouteImport.update({
  id: '/acerca-de-nosotros',
  path: '/acerca-de-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acerca-de-nosotros': typeof AcercaDeNosotrosRoute
  '/calidad': typeof CalidadRoute
  '/contacto': typeof ContactoRoute
  '/links-de-interes': typeof LinksDeInteresRoute
  '/normativas': typeof NormativasRoute
  '/planes': typeof PlanesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acerca-de-nosotros': typeof AcercaDeNosotrosRoute
  '/calidad': typeof CalidadRoute
  '/contacto': typeof ContactoRoute
  '/links-de-interes': typeof LinksDeInteresRoute
  '/normativas': typeof NormativasRoute
  '/planes': typeof PlanesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acerca-de-nosotros': typeof AcercaDeNosotrosRoute
  '/calidad': typeof CalidadRoute
  '/contacto': typeof ContactoRoute
  '/links-de-interes': typeof LinksDeInteresRoute
  '/normativas': typeof NormativasRoute
  '/planes': typeof PlanesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acerca-de-nosotros'
    | '/calidad'
    | '/contacto'
    | '/links-de-interes'
    | '/normativas'
    | '/planes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acerca-de-nosotros'
    | '/calidad'
    | '/contacto'
    | '/links-de-interes'
    | '/normativas'
    | '/planes'
  id:
    | '__root__'
    | '/'
    | '/acerca-de-nosotros'
    | '/calidad'
    | '/contacto'
    | '/links-de-interes'
    | '/normativas'
    | '/planes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcercaDeNosotrosRoute: typeof AcercaDeNosotrosRoute
  CalidadRoute: typeof CalidadRoute
  ContactoRoute: typeof ContactoRoute
  LinksDeInteresRoute: typeof LinksDeInteresRoute
  NormativasRoute: typeof NormativasRoute
  PlanesRoute: typeof PlanesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/normativas': {
      id: '/normativas'
      path: '/normativas'
      fullPath: '/normativas'
      preLoaderRoute: typeof NormativasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links-de-interes': {
      id: '/links-de-interes'
      path: '/links-de-interes'
      fullPath: '/links-de-interes'
      preLoaderRoute: typeof LinksDeInteresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calidad': {
      id: '/calidad'
      path: '/calidad'
      fullPath: '/calidad'
      preLoaderRoute: typeof CalidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acerca-de-nosotros': {
      id: '/acerca-de-nosotros'
      path: '/acerca-de-nosotros'
      fullPath: '/acerca-de-nosotros'
      preLoaderRoute: typeof AcercaDeNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcercaDeNosotrosRoute: AcercaDeNosotrosRoute,
  CalidadRoute: CalidadRoute,
  ContactoRoute: ContactoRoute,
  LinksDeInteresRoute: LinksDeInteresRoute,
  NormativasRoute: NormativasRoute,
  PlanesRoute: PlanesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
